# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: raft.proto
# Protobuf Python Version: 6.30.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    2,
    '',
    'raft.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nraft.proto\"%\n\x08LogEntry\x12\x0b\n\x03\x63md\x18\x01 \x01(\t\x12\x0c\n\x04term\x18\x02 \x01(\x03\"b\n\x12RequestVoteRequest\x12\x0c\n\x04term\x18\x01 \x01(\x03\x12\x13\n\x0b\x63\x61ndidateId\x18\x02 \x01(\t\x12\x14\n\x0clastLogIndex\x18\x03 \x01(\x03\x12\x13\n\x0blastLogTerm\x18\x04 \x01(\x03\"8\n\x13RequestVoteResponse\x12\x0c\n\x04term\x18\x01 \x01(\x03\x12\x13\n\x0bvoteGranted\x18\x02 \x01(\x08\"\x93\x01\n\x14\x41ppendEntriesRequest\x12\x0c\n\x04term\x18\x01 \x01(\x03\x12\x10\n\x08leaderId\x18\x02 \x01(\t\x12\x14\n\x0cprevLogIndex\x18\x03 \x01(\x03\x12\x13\n\x0bprevLogTerm\x18\x04 \x01(\x03\x12\x1a\n\x07\x65ntries\x18\x05 \x03(\x0b\x32\t.LogEntry\x12\x14\n\x0cleaderCommit\x18\x06 \x01(\x03\"L\n\x15\x41ppendEntriesResponse\x12\x0c\n\x04term\x18\x01 \x01(\x03\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\x14\n\x0clastLogIndex\x18\x03 \x01(\x03\"\xe1\x01\n\x07Message\x12+\n\x0crequest_vote\x18\x01 \x01(\x0b\x32\x13.RequestVoteRequestH\x00\x12\x35\n\x15request_vote_response\x18\x02 \x01(\x0b\x32\x14.RequestVoteResponseH\x00\x12/\n\x0e\x61ppend_entries\x18\x03 \x01(\x0b\x32\x15.AppendEntriesRequestH\x00\x12\x39\n\x17\x61ppend_entries_response\x18\x04 \x01(\x0b\x32\x16.AppendEntriesResponseH\x00\x42\x06\n\x04Typeb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'raft_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LOGENTRY']._serialized_start=14
  _globals['_LOGENTRY']._serialized_end=51
  _globals['_REQUESTVOTEREQUEST']._serialized_start=53
  _globals['_REQUESTVOTEREQUEST']._serialized_end=151
  _globals['_REQUESTVOTERESPONSE']._serialized_start=153
  _globals['_REQUESTVOTERESPONSE']._serialized_end=209
  _globals['_APPENDENTRIESREQUEST']._serialized_start=212
  _globals['_APPENDENTRIESREQUEST']._serialized_end=359
  _globals['_APPENDENTRIESRESPONSE']._serialized_start=361
  _globals['_APPENDENTRIESRESPONSE']._serialized_end=437
  _globals['_MESSAGE']._serialized_start=440
  _globals['_MESSAGE']._serialized_end=665
# @@protoc_insertion_point(module_scope)
